import type { Metadata } from "next";
import { Open_Sans, Noto_Sans, Lato, Roboto } from 'next/font/google'
import "../styles/globals.css";
import Script from 'next/script';
/*
import localFont from "next/font/local";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/

// app/layout.tsx


const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' })
const notoSans = Noto_Sans({ subsets: ['latin'], variable: '--font-noto-sans' })
const lato = Lato({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-lato' })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-roboto' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${openSans.variable} ${notoSans.variable} ${lato.variable} ${roboto.variable}`}>
      <head>
        <Script
          src="https://cloud.umami.is/script.js"
          data-website-id="eca7ade8-1f83-4309-b1d4-6d2f5fbe7173"
          strategy="afterInteractive"
        />
      </head>
      <body>{children}</body>
    </html>
  )
}