// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
import {
  Code,
  Layout,
  Smartphone,
  TrendingUp,
  Users,
  ShieldCheck,
  ArrowRight,
  Globe,
  Monitor,
  Settings,
  Gauge,
  Repeat,
  Search,
  ClipboardList,
  Paintbrush,
  Rocket,
  Clock,
  Workflow,
  FileCode,
  HeadphonesIcon,
  Brain,
  MapPin,
  MessageCircle,
  ShoppingCart,
  BarChart3,
  Heart,
  Store,
  GraduationCap,
  Briefcase,
  FileJson2,
  Bot,
  Mic,
  UserCheck,
  Share2,
  FileText,
  BarChart,
  SquareSplitHorizontal,
  DollarSign,
  Eye,
  ArrowUpCircle,
  Handshake,
  Package,
  Award,
  Home,
  ChartLine,
  Cloud,
  Cpu,
  Cog,
  Shield,
  Layers,
  MonitorCog,
  CodeXml,
  Headphones,
  HandCoins,
  TestTube,
  Server,
  Truck,
  Code2,
  CheckCircle,
  ChevronUp,
  ChevronDown
} from 'lucide-react';

// Map of icon names to components
export const IconRegistry = {
  'Code': Code,
  'Layout': Layout,
  'Smartphone': Smartphone,
  'TrendingUp': TrendingUp,
  'Users': Users,
  'ShieldCheck': ShieldCheck,
  'ArrowRight': ArrowRight,
  'Globe': Globe,
  'Monitor': Monitor,
  'Settings': Settings,
  'Gauge': Gauge,
  'Repeat': Repeat,
  'Search': Search,
  'ClipboardList': ClipboardList,
  'Paintbrush': Paintbrush,
  'Rocket': Rocket,
  'Clock': Clock,
  'Workflow': Workflow,
  'FileCode': FileCode,
  'HeadphonesIcon': HeadphonesIcon,
  'Brain': Brain,
  'MapPin': MapPin,
  'MessageCircle': MessageCircle,
  'ShoppingCart': ShoppingCart,
  'BarChart3': BarChart3,
  'Heart': Heart,
  'Store': Store,
  'GraduationCap': GraduationCap,
  'Briefcase': Briefcase,
  'FileJson2': FileJson2,
  'Bot': Bot,
  'Mic': Mic,
  'UserCheck': UserCheck,
  'Share2': Share2,
  'FileText': FileText,
  'BarChart': BarChart,
  'SquareSplitHorizontal': SquareSplitHorizontal,
  'DollarSign': DollarSign,
  'Eye': Eye,
  'ArrowUpCircle': ArrowUpCircle,
  'Handshake': Handshake,
  'Package': Package,
  'Award': Award,
  'Home': Home,
  'ChartLine': ChartLine,
  'Cloud': Cloud,
  'Cpu': Cpu,
  'Cog': Cog,
  'Shield': Shield,
  'Layers': Layers,
  'MonitorCog': MonitorCog,
  'CodeXml': CodeXml,
  'Headphones': Headphones,
  'HandCoins': HandCoins,
  'TestTube': TestTube,
  'Server': Server,
  'Truck': Truck,
  'Code2': Code2,
  'CheckCircle': CheckCircle,
  'ChevronUp': ChevronUp,
  'ChevronDown': ChevronDown
};

// Type for icon names
export type IconName = keyof typeof IconRegistry;

// Helper function to get an icon component from its name
export function getIcon(name: string) {
  return IconRegistry[name as IconName] || IconRegistry['Code'];
}
