// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
import {
  Code,
  Layout,
  Smartphone,
  TrendingUp,
  Users,
  ShieldCheck,
  ArrowRight,
  Globe,
  Monitor,
  Settings,
  Gauge,
  Repeat,
  FileJson2,
  Search,
  ClipboardList,
  Paintbrush,
  Rocket,
  Clock,
  Workflow,
  FileCode,
  HeadphonesIcon,
  Brain,
  MapPin,
  MessageCircle,
  ShoppingCart,
  BarChart3,
  Heart,
  Store,
  GraduationCap,
  Briefcase,
  Bot,
  Mic,
  UserCheck,
  Share2,
  FileText,
  BarChart,
  SquareSplitHorizontal,
  DollarSign,
  Eye,
  ArrowUpCircle,
  Handshake,
  Package,
  Award,
  Home,
  ChartLine,
  Minimize2,
  Palette,
  Zap,
  Image,
  Layers,
  PenTool,
  Film,
  Target,
  Maximize,
  Lightbulb,
  Copyright,
  ShoppingBag,
  Coffee,
  BookOpen,
  CloudRain,
  Shield,
  LineChart,
  FlaskConical,
  PieChart,
  Database,
  Compass,
  BarChart2,
  Presentation,
  MessageSquare,
  Lock,
  Factory,
  Stethoscope,
  Cloud,
  Cpu,
  Cog,
  MonitorCog,
  CodeXml,
  Headphones,
  HandCoins,
  TestTube,
  Server,
  Truck,
  Code2,
  RefreshCw,
  FileChartColumn,
  Hammer,
  LifeBuoy,
  CheckCircle,
  GitMerge,
  CodeSquare,
  Scale,
  HelpCircle,
  ChevronUp,
  ChevronDown
} from 'lucide-react';

// Map of icon names to components
export const IconRegistry = {
  'Code': Code,
  'Layout': Layout,
  'Smartphone': Smartphone,
  'TrendingUp': TrendingUp,
  'Users': Users,
  'ShieldCheck': ShieldCheck,
  'ArrowRight': ArrowRight,
  'Globe': Globe,
  'Monitor': Monitor,
  'Settings': Settings,
  'Gauge': Gauge,
  'Repeat': Repeat,
  'FileJson2': FileJson2,
  'Search': Search,
  'ClipboardList': ClipboardList,
  'Paintbrush': Paintbrush,
  'Rocket': Rocket,
  'Clock': Clock,
  'Workflow': Workflow,
  'FileCode': FileCode,
  'HeadphonesIcon': HeadphonesIcon,
  'Brain': Brain,
  'MapPin': MapPin,
  'MessageCircle': MessageCircle,
  'ShoppingCart': ShoppingCart,
  'BarChart3': BarChart3,
  'Heart': Heart,
  'Store': Store,
  'GraduationCap': GraduationCap,
  'Briefcase': Briefcase,
  'Bot': Bot,
  'Mic': Mic,
  'UserCheck': UserCheck,
  'Share2': Share2,
  'FileText': FileText,
  'BarChart': BarChart,
  'SquareSplitHorizontal': SquareSplitHorizontal,
  'DollarSign': DollarSign,
  'Eye': Eye,
  'ArrowUpCircle': ArrowUpCircle,
  'Handshake': Handshake,
  'Package': Package,
  'Award': Award,
  'Home': Home,
  'ChartLine': ChartLine,
  'Minimize2': Minimize2,
  'Palette': Palette,
  'Zap': Zap,
  'Image': Image,
  'Layers': Layers,
  'PenTool': PenTool,
  'Film': Film,
  'Target': Target,
  'Maximize': Maximize,
  'Lightbulb': Lightbulb,
  'Copyright': Copyright,
  'ShoppingBag': ShoppingBag,
  'Coffee': Coffee,
  'BookOpen': BookOpen,
  'CloudRain': CloudRain,
  'Shield': Shield,
  'LineChart': LineChart,
  'FlaskConical': FlaskConical,
  'PieChart': PieChart,
  'Database': Database,
  'Compass': Compass,
  'BarChart2': BarChart2,
  'Presentation': Presentation,
  'MessageSquare': MessageSquare,
  'Lock': Lock,
  'Factory': Factory,
  'Stethoscope': Stethoscope,
  'Cloud': Cloud,
  'Cpu': Cpu,
  'Cog': Cog,
  'MonitorCog': MonitorCog,
  'CodeXml': CodeXml,
  'Headphones': Headphones,
  'HandCoins': HandCoins,
  'TestTube': TestTube,
  'Server': Server,
  'Truck': Truck,
  'Code2': Code2,
  'RefreshCw': RefreshCw,
  'FileChartColumn': FileChartColumn,
  'Hammer': Hammer,
  'LifeBuoy': LifeBuoy,
  'CheckCircle': CheckCircle,
  'GitMerge': GitMerge,
  'CodeSquare': CodeSquare,
  'Scale': Scale,
  'HelpCircle': HelpCircle,
  'ChevronUp': ChevronUp,
  'ChevronDown': ChevronDown
};

// Type for icon names
export type IconName = keyof typeof IconRegistry;

// Helper function to get an icon component from its name
export function getIcon(name: string) {
  return IconRegistry[name as IconName] || IconRegistry['Code'];
}
