// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
import {
  Code,
  Layout,
  Globe,
  Smartphone,
  TrendingUp,
  Users,
  ShieldCheck,
  ArrowRight,
  Monitor,
  Settings,
  Gauge,
  Repeat,
  LayoutGrid,
  Search,
  ClipboardList,
  Paintbrush,
  Rocket,
  Clock,
  Workflow,
  FileCode,
  HeadphonesIcon,
  Brain,
  MapPin,
  MessageCircle,
  ShoppingCart,
  BarChart3,
  Heart,
  Store,
  GraduationCap,
  Briefcase,
  Cloud,
  Bot,
  Cpu,
  Cog,
  Shield,
  Layers,
  MonitorCog,
  CodeXml,
  Headphones,
  HandCoins,
  Handshake,
  TestTube,
  Server,
  Truck,
  Code2,
  CheckCircle,
  ChevronUp,
  ChevronDown
} from 'lucide-react';

// Map of icon names to components
export const IconRegistry = {
  'Code': Code,
  'Layout': Layout,
  'Globe': Globe,
  'Smartphone': Smartphone,
  'TrendingUp': TrendingUp,
  'Users': Users,
  'ShieldCheck': ShieldCheck,
  'ArrowRight': ArrowRight,
  'Monitor': Monitor,
  'Settings': Settings,
  'Gauge': Gauge,
  'Repeat': Repeat,
  'LayoutGrid': LayoutGrid,
  'Search': Search,
  'ClipboardList': ClipboardList,
  'Paintbrush': Paintbrush,
  'Rocket': Rocket,
  'Clock': Clock,
  'Workflow': Workflow,
  'FileCode': FileCode,
  'HeadphonesIcon': HeadphonesIcon,
  'Brain': Brain,
  'MapPin': MapPin,
  'MessageCircle': MessageCircle,
  'ShoppingCart': ShoppingCart,
  'BarChart3': BarChart3,
  'Heart': Heart,
  'Store': Store,
  'GraduationCap': GraduationCap,
  'Briefcase': Briefcase,
  'Cloud': Cloud,
  'Bot': Bot,
  'Cpu': Cpu,
  'Cog': Cog,
  'Shield': Shield,
  'Layers': Layers,
  'MonitorCog': MonitorCog,
  'CodeXml': CodeXml,
  'Headphones': Headphones,
  'HandCoins': HandCoins,
  'Handshake': Handshake,
  'TestTube': TestTube,
  'Server': Server,
  'Truck': Truck,
  'Code2': Code2,
  'CheckCircle': CheckCircle,
  'ChevronUp': ChevronUp,
  'ChevronDown': ChevronDown
};

// Type for icon names
export type IconName = keyof typeof IconRegistry;

// Helper function to get an icon component from its name
export function getIcon(name: string) {
  return IconRegistry[name as IconName] || IconRegistry['Code'];
}
